language: python
python:
  - 3.8
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=quality_of_life --cov-fail-under=65 tests
  - black quality_of_life --diff
  - flake8 quality_of_life
  - python setup.py sdist bdist_wheel
  - docker build -t quality_of_life .
